### PR TITLE
Update Voting.sol

### PR DESCRIPTION
**Pull request by dheerajd5**
#24 
We can use the block chain in this way right, cause if you get the details of a candidate, you get the subsequent details of the rest of the candidates. Is this the right way to solve the issue, or am I doing something wrong?

### CODE REVIEW

**Comment by saitejach127** [comment]
Can you tag which issue are you solving

**Comment by dheerajd5** [comment]
> Can you tag which issue are you solving

Sorry for the inconvience, #22

**Comment by saitejach127** [comment]
Your pr is good but works only if one candidate is there. But there will be many candidates normally. So an array of candidates will be passed to the constructor. That needs to be set as candidates. Make these changes

**Comment by dheerajd5** [comment]
Will these array of candidates passed into constructor include the names and the cross checking of whether the names repeat?

**Comment by saitejach127** [comment]
I think no need of cross checking for now. Duplictes mostly wont be there. Also candidates names only will be passed

**Comment by dheerajd5** [comment]
If there passed array will have the names, we can just directly assign the list to the class variable, like I did now right?

**Comment by saitejach127** [comment]
Ya directly assigning will be enough

**Pull request merged**
